### ISSUE TITLE
Issue with generating PDF file when using millimeters unit via the website (makebox.io)

### ISSUE THREAD

**Issue by carelh** [kigster/laser-cutter#10]
The generation of the PDF file using any of the known supported web browsers on either Windows 7 or Mac OS X Sierra, causes the resulting PDF file to be blank when opened with Adobe Acrobat Reader. Mac OS Preview is able to show something but the box design is overlapping each of the sides. When the resulting PDF file is opened in CorelDraw X7, the measurements are off and shows up in "meters" and not millimeters as expected.

[makeabox-200.00W-350.00H-200.00D-5.00T-20170501131243_correctlygenerated.pdf](https://github.com/kigster/laser-cutter/files/1040836/makeabox-200.00W-350.00H-200.00D-5.00T-20170501131243_correctlygenerated.pdf)
[makeabox-200.00W-100.00H-200.00D-5.00T-20170531043053_infobox.pdf](https://github.com/kigster/laser-cutter/files/1040837/makeabox-200.00W-100.00H-200.00D-5.00T-20170531043053_infobox.pdf)
[makeabox-200.00W-100.00H-200.00D-5.00T-20170531042033.pdf](https://github.com/kigster/laser-cutter/files/1040838/makeabox-200.00W-100.00H-200.00D-5.00T-20170531042033.pdf)
![makebox_io_screenshot_chrome](https://cloud.githubusercontent.com/assets/19525163/26624647/cdc65d98-45f1-11e7-81d4-90b79aa4fe69.png)

**Comment by kigster** [comment]
Could you test this on the current build?

**Comment by carelh** [comment]
Hi Kigster, the problem is resolved from the web interface. generating a pdf file (unit in millimeters) from makebox.io generates a correct PDF file and also pulls in correctly in CorelDraw X7/X8. thanks!
