### ISSUE TITLE
"Include dimensions?"-checkbox doesn't seem to be working

### ISSUE THREAD

**Issue by tokefrello** [kigster/laser-cutter#5]
Whether I check the "Include dimensions?" box or not, dimension details are included in the final PDF (see picture).
![skaermbillede 2016-05-17 kl 10 20 05](https://cloud.githubusercontent.com/assets/1197378/15315620/07c226fc-1c19-11e6-8c15-786b49aece31.png)

**Comment by kigster** [comment]
This is fixed now, and is live.
